name: "Test"

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v5"
      - uses: "actions/setup-node@v5"
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Generate schema
        run: npm run codegen
      - name: Check types
        run: npm run check:types
      - name: Run tests
        run: npm t
